name: Build .deb packages
on:
  push:
    branches:
      - 'qubes/**'
  workflow_dispatch:

jobs:
  build_debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jtdor/build-deb-action@v1
        with:
          extra-build-deps: wget ca-certificates
          before-build-hook: |
            debian/rules get-orig-source
            mkdir amd64 arm64
            tar xvf *amd64.tar.gz -C amd64 --strip-components 1
            tar xvf *arm64.tar.gz -C arm64 --strip-components 1
          buildpackage-opts: -us -uc --build=binary
      - uses: actions/upload-artifact@v7
        with:
          name: deb-output
          path: debian/artifacts/
